# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.java.home=/home/riley/.minecraft/runtime/java-runtime-epsilon/linux/java-runtime-epsilon

# NeoForge Properties
minecraft_version=26.1.2
neo_version=26.1.2.100

mod_id=vulkanmod

# Mod Properties
mod_version=0.6.8+26.1.2
maven_group=net.vulkanmod
archives_base_name=VulkanMod_26.1.2
