modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0"

[[mods]]
modId = "vulkanmod"
version = "${version}"
displayName = "VulkanMod"
authors = "xCollateral"
description = '''
Bring Vulkan to Minecraft!
'''
logoFile = "assets/vulkanmod/vlogo.png"

[[dependencies.vulkanmod]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2.78,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vulkanmod]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "vulkanmod.mixins.json"
