#version 450

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (push_constant) uniform pushConstant {
    vec2 srcTexelSize;
};

//https://www.khronos.org/opengl/wiki/Image_Load_Store
layout(binding = 0) uniform sampler2D srcTexture;
layout(binding = 1, rgba16f) uniform image2D outImage;

const float filterRadius = 0.005f;

void main() {
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(pixelCoord, imageSize(outImage)))) return;
    vec2 texCoord = (pixelCoord + 0.5) * srcTexelSize;

    // The filter kernel is applied with a radius, specified in texture
    // coordinates, so that the radius will vary across mip resolutions.
    float x = filterRadius * srcTexelSize.x;
    float y = filterRadius * srcTexelSize.y;

    // Take 9 samples around current texel:
    // a - b - c
    // d - e - f
    // g - h - i
    // === ('e' is the current texel) ===
    vec3 a = texture(srcTexture, vec2(texCoord.x - x, texCoord.y + y)).rgb;
    vec3 b = texture(srcTexture, vec2(texCoord.x,     texCoord.y + y)).rgb;
    vec3 c = texture(srcTexture, vec2(texCoord.x + x, texCoord.y + y)).rgb;

    vec3 d = texture(srcTexture, vec2(texCoord.x - x, texCoord.y)).rgb;
    vec3 e = texture(srcTexture, vec2(texCoord.x,     texCoord.y)).rgb;
    vec3 f = texture(srcTexture, vec2(texCoord.x + x, texCoord.y)).rgb;

    vec3 g = texture(srcTexture, vec2(texCoord.x - x, texCoord.y - y)).rgb;
    vec3 h = texture(srcTexture, vec2(texCoord.x,     texCoord.y - y)).rgb;
    vec3 i = texture(srcTexture, vec2(texCoord.x + x, texCoord.y - y)).rgb;

    vec3 upsample;
    // Apply weighted distribution, by using a 3x3 tent filter:
    //  1   | 1 2 1 |
    // -- * | 2 4 2 |
    // 16   | 1 2 1 |
    upsample = e*4.0;
    upsample += (b+d+f+h)*2.0;
    upsample += (a+c+g+i);
    upsample *= 1.0 / 16.0;

    //    vec3 l = texture(srcTexture, vec2(texCoord.x - texelSize.x,     texCoord.y)).rgb;
    //    vec3 c = texture(srcTexture, vec2(texCoord.x,     texCoord.y)).rgb;
    //    vec3 r = texture(srcTexture, vec2(texCoord.x + texelSize.x,     texCoord.y)).rgb;
    //
    //    upsample = c;
    //    upsample += l;
    //    upsample += r;
    //    upsample *= 1.0 / 3.0;

    vec3 blend = imageLoad(outImage, ivec2(pixelCoord)).rgb + upsample;

    imageStore(outImage, ivec2(pixelCoord), vec4(blend, 1.0));
}

////https://github.com/Shot511/RapidGL/blob/master/src/demos/26_bloom
//#version 460
//
//layout(binding = 0)			 uniform sampler2D u_input_texture;
//layout(rgba32f, binding = 0) uniform image2D   u_output_image;
//
//layout(binding = 1)			 uniform sampler2D u_dirt_texture;
//
//uniform vec2  u_texel_size;
//uniform int   u_mip_level;
//uniform float u_bloom_intensity;
//uniform float u_dirt_intensity;
//
//#define GROUP_SIZE         8
//#define GROUP_THREAD_COUNT (GROUP_SIZE * GROUP_SIZE)
//#define FILTER_SIZE        3
//#define FILTER_RADIUS      (FILTER_SIZE / 2)
//#define TILE_SIZE          (GROUP_SIZE + 2 * FILTER_RADIUS)
//#define TILE_PIXEL_COUNT   (TILE_SIZE * TILE_SIZE)
//
//shared float sm_r[TILE_PIXEL_COUNT];
//shared float sm_g[TILE_PIXEL_COUNT];
//shared float sm_b[TILE_PIXEL_COUNT];
//
//void store_lds(int idx, vec4 c)
//{
//    sm_r[idx] = c.r;
//    sm_g[idx] = c.g;
//    sm_b[idx] = c.b;
//}
//
//vec4 load_lds(uint idx)
//{
//    return vec4(sm_r[idx], sm_g[idx], sm_b[idx], 1.0);
//}
//
//layout(local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE) in;
//void main()
//{
//    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
//    vec2  base_index   = ivec2(gl_WorkGroupID) * GROUP_SIZE - FILTER_RADIUS;
//
//    // The first (TILE_PIXEL_COUNT - GROUP_THREAD_COUNT) threads load at most 2 texel values
//    for (int i = int(gl_LocalInvocationIndex); i < TILE_PIXEL_COUNT; i += GROUP_THREAD_COUNT)
//    {
//        vec2 uv        = (base_index + 0.5) * u_texel_size;
//        vec2 uv_offset = vec2(i % TILE_SIZE, i / TILE_SIZE) * u_texel_size;
//
//        vec4 color = textureLod(u_input_texture, (uv + uv_offset), u_mip_level);
//        store_lds(i, color);
//    }
//
//    memoryBarrierShared();
//    barrier();
//
//    // center texel
//    uint sm_idx = (gl_LocalInvocationID.x + FILTER_RADIUS) + (gl_LocalInvocationID.y + FILTER_RADIUS) * TILE_SIZE;
//
//    // Based on [Jimenez14] http://goo.gl/eomGso
//    vec4 s;
//    s =  load_lds(sm_idx - TILE_SIZE - 1);
//    s += load_lds(sm_idx - TILE_SIZE    ) * 2.0;
//    s += load_lds(sm_idx - TILE_SIZE + 1);
//
//    s += load_lds(sm_idx - 1) * 2.0;
//    s += load_lds(sm_idx    ) * 4.0;
//    s += load_lds(sm_idx + 1) * 2.0;
//
//    s += load_lds(sm_idx + TILE_SIZE - 1);
//    s += load_lds(sm_idx + TILE_SIZE    ) * 2.0;
//    s += load_lds(sm_idx + TILE_SIZE + 1);
//
//    vec4 bloom = s * (1.0 / 16.0);
//
//    vec4 out_pixel = imageLoad(u_output_image, pixel_coords);
//    out_pixel += bloom * u_bloom_intensity;
//
//    if (u_mip_level == 1)
//    {
//        vec2  uv  = (vec2(pixel_coords) + vec2(0.5, 0.5)) * u_texel_size;
//        out_pixel += texture(u_dirt_texture, uv) * u_dirt_intensity * bloom * u_bloom_intensity;
//    }
//
//    imageStore(u_output_image, pixel_coords, out_pixel);
//}